#684 Wiremock Extensions
tomakehurst/wiremock pull request #1439
Opened 2021-03-30 17:38 UTC by Patouche

2021-03-31 15:50 UTC, tomakehurst commented
Thank you for contributing this. I'm a bit snowed-under at the moment, but I'll try and take a look tomorrow and provide some feedback.

2021-03-31 17:36 UTC, Patouche commented
Yes, no problem. Take your time. There is no constraint no my side.

2021-04-14 10:00 UTC, tomakehurst requested changes
I've done a quick pass over what you've done so far. I like the ability to choose multiple means of injection.

Please see my inline comments for a few things I think could be improved in.

2021-04-15 22:12 UTC, Patouche commented on build.gradle
> +    testImplementation("org.junit.jupiter:junit-jupiter")
Yes, 

With this syntax, we cannot use bom import. Still, you're right. It's probably better to keep the same syntax everywhere.

I update the commit to cleanup the `build.gradle` file.

2021-04-15 22:17 UTC, Patouche commented on build.gradle
>      testCompile 'org.mockito:mockito-core:2.28.2'
Yes, sorry, my mistake.

It was only to take a look at another mock library to get inspiration from what they're doing. In fact, Mockito is maybe not be the best for it. I just forgot to delete these lines

2021-08-24 21:47 UTC, tomakehurst commented
I've taken this and re-worked the design (quite) a bit.

It's now all pushed on a branch and you can find the docs here: https://github.com/tomakehurst/wiremock/blob/junit-jupiter/docs-v2/_docs/junit-jupiter.md

Feedback appreciated on whether this will do everything you need and is intuitive to use. If anyone needs a beta build to try out please let me know.

2021-08-24 21:48 UTC, tomakehurst commented
Acceptance tests are here if you'd like to see it all put together: https://github.com/tomakehurst/wiremock/tree/junit-jupiter/src/test/java/com/github/tomakehurst/wiremock/junit5

2021-08-25 15:39 UTC, rieckpil commented
@tomakehurst this looks great 🚀  I'd be happy to test a beta build

2021-08-29 16:55 UTC, rieckpil commented
It works excellent - I gave it a shot for a Spring Boot project and used both the declarative and programmatic approach 🚀 I'm looking forward to removing some boilerplate code in many projects 👍

2021-09-11 21:01 UTC, timtebeek commented
Just want to say the `WireMockExtension` as seen in 2.31.0 works perfectly for our use cases as well, glad to see this added.

One question I have though is that we are extending `WireMockExtension` in classes that each replicate external services that we integrate with. That way we can offer more high level methods to stub requests for these services as separately registered extensions. I did not see this pattern mentioned in the docs, but it appears to work well. Is extending `WireMockExtension` (un)officially supported?

We wouldn't want to paint ourselves into a corner only to find this option dropped in later versions for instance.

2021-09-13 09:41 UTC, tomakehurst commented
This is a very good question @timtebeek. Since the JUnit 4 rule supports extension I think it's fair that the Jupiter extension should too.

I'll add some  lifecycle template methods and documentation in the next release, and give some thought to guaranteeing no breaking changes.

2021-09-13 09:55 UTC, timtebeek commented
Awesome thanks! To be clear: we are not overriding any methods from WireMockExtension for the moment, so you're welcome to make methods such as `getRuntimeInfo()` and `baseUrl()` final until a convincing use case to loosen those restrictions comes up.

We are however calling the `protected WireMockExtension(Options options, boolean configureStaticDsl, boolean failOnUnmatchedRequests, boolean proxyMode)` constructor, which has a comment above it `// Intended to be called from the builder`. We need that constructor as we want to pass Options with a separate port per extension instance, and as a consequence of that we also pass the three booleans required. Could be worthwhile to update the comment to reflect use by subclasses.

2021-09-13 10:06 UTC, tomakehurst commented
OK, looks like the constructor is where some thought will be required. I'd quite like to avoid an explosion of constructor overloads over time as more options are added.

2021-09-14 11:32 UTC, tomakehurst commented
Released in 2.31.0

2021-09-14 11:32 UTC, closed without merging